version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - dev
  - master
image: Ubuntu1804
environment:
  docker_username:
    secure: wd3cSJUV7vB6IIESHMi+0g==
  docker_password:
    secure: 4J+d4lDlZxOuAdTbnKjn2+ZzScAHYgyxprDkCGS6btVGHUqbyMDSk0nQV30T6rsP
  docker_owner: vladikan
build_script:
- sh: >-
    docker login -u $docker_username -p $docker_password


    name="$docker_owner/addrss-telegram"

    version=$APPVEYOR_BUILD_VERSION


    if [ "$APPVEYOR_REPO_BRANCH" == "master" ]; then
      docker build -t "$name:latest" -t "$name:$version" .
    else
      docker build -t "$name":preview .
    fi


    docker push "$name" --all-tags