version: '3'

services:
    postgres:
        image: postgres:latest
        container_name: "postgres"
        hostname: "postgres"
        restart: always
        ports:
          - 5432:5432
        volumes:
          - pgdata:/var/lib/postgresql/data
          - ./deploy:/docker-entrypoint-initdb.d/
        environment:
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=admin
          - POSTGRES_DB=feed

volumes:
    pgdata: