version: '3'

services:
    postgres:
      image: postgres:latest
      container_name: "postgres"
      hostname: "postgres"
      restart: always
      
      volumes:
        - pgdata:/var/lib/postgresql/data
        - ./deploy:/docker-entrypoint-initdb.d/
      
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=feed

    addrss:
      image: vladikan/addrss-telegram:latest
      container_name: "addrss"
      hostname: "addrss"
      restart: always
      
      depends_on:
        - postgres
  
      logging:
        driver: json-file
        options:
            max-size: "5m"
            max-file: "5"
  
      environment:
        - AR_TOKEN
        - AR_DATABASE=postgres://admin:admin@postgres/feed
        - AR_DEBUG=false
        - AR_READER_INTERVAL
        - AR_READER_FEEDS
        
volumes:
    pgdata: