version: '3'

services:
    postgres:
      ports:
        - 5432:5432

    addrss:
      image: vladikan/addrss:latest
      build: .
      environment:
        - AR_TOKEN=1380627833:AAGxvCYoNz_JVR2XGkmtZxDqr1Fs1vj3tNU
        - AR_BOT_ADMIN=348071017
        - AR_DATABASE=postgres://admin:admin@postgres/feed